server:
  port: 7007
spring:
  application:
    name: zuul-sever
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
    fetch-registry: true


zuul:
  servlet-path: /zuul
  routes:
    provider:
      path: /provider/**
      serviceId: provider
    consumer:
      path: /consumer/**
      serviceId: consumer