server:
  port: 7004
spring:
  application:
    name: consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
    fetch-registry: true
feign:
  hystrix:
    enabled: true
#  instance:
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}


