server:
  port: 7003
spring:
  application:
    name: provider

management:
  endpoints:
    web:
      exposure:
        include: refresh

#  instance:
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}