server:
  port: 7005
spring:
  application:
    name: provider
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: refresh
stanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}