server:
  port: 7005
spring:
  application:
    name: provider

management:
  endpoints:
    web:
      exposure:
        include: refresh
stanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}